import React from 'react';
import {
	Logo,
	Gastroenterologist,
	Stethoscope,
	BackArrow,
	Basket,
	Calendar,
	Tick,
	Info,
	Caller,
	ArrowDown,
	Spinner,
	Rupee,
	Files,
	Orders,
	Coverage,
	Prescription,
	LabReport,
	AddDate,
	Complaint,
	Advice,
	Diagnosis,
	Notes,
	DateSlot,
	Lock,
	Location,
	NoTransaction,
	CardInnerLogo,
	InsuranceCardLogo,
	Diagnostic,
	Pharmacy,
	Close,
	PolicyDoc,
	HealthCheck,
	LabDiagnostic,
	Home,
	Office,
	Ellipsis,
	Logout,
	QuestionMark,
	Collapse,
	NoStore,
	NoMedicine,
	Edit,
	Delete,
	Search,
	LocationPin,
	Swicth,
	Video,
	Clinic,
	Clock,
	Alert,
	GmapPin,
	AddCart,
	RemoveItem,
	WelcomeIcon,
	ShowPassword,
	HidePassword,
	Success,
	SuccessTick,
	Loading,
	LoginSuccess,
	PhoneHandler,
	PhoneHandle,
	Logoutscreen,
	LocationPoint,
	OrderCancelImgLarge,
	LegalIcon
} from './icons';

export const iconNames = {
	logo: Logo,
	gastroenterologist: Gastroenterologist,
	stethoscope: Stethoscope,
	backArrow: BackArrow,
	basket: Basket,
	calendar: Calendar,
	tick: Tick,
	info: Info,
	caller: Caller,
	arrowDown: ArrowDown,
	spinner: Spinner,
	rupee: Rupee,
	files: Files,
	orders: Orders,
	coverage: Coverage,
	prescription: Prescription,
	labreport: LabReport,
	addDate: AddDate,
	complaint: Complaint,
	advice: Advice,
	diagnosis: Diagnosis,
	notes: Notes,
	dateSlot: DateSlot,
	lock: Lock,
	location: Location,
	noTransaction: NoTransaction,
	cardInnerLogo: CardInnerLogo,
	InsuranceCardLogo: InsuranceCardLogo,
	diagnostic: Diagnostic,
	pharmacy: Pharmacy,
	close: Close,
	policydoc: PolicyDoc,
	healthCheck: HealthCheck,
	labDiagnostic: LabDiagnostic,
	Home: Home,
	Office: Office,
	Ellipsis: Ellipsis,
	logout: Logout,
	questionmark: QuestionMark,
	collapse: Collapse,
	edit: Edit,
	delete: Delete,
	search: Search,
	locationPin: LocationPin,
	swicth: Swicth,
	video: Video,
	clinic: Clinic,
	clock: Clock,
	nostore: NoStore,
	noMedicine: NoMedicine,
	gmappin: GmapPin,
	alert: Alert,
	addcart: AddCart,
	removeItem: RemoveItem,
	WelcomeIcon: WelcomeIcon,
	showPass: ShowPassword,
	hidePass: HidePassword,
	success: Success,
	successTick: SuccessTick,
	loading: Loading,
	loginSuccess: LoginSuccess,
	phoneHandler: PhoneHandler,
	phoneHandle: PhoneHandle,
	logoutscreen:Logoutscreen,
	locationPoint: LocationPoint,
	legalIcon: LegalIcon,
	OrderCancelImgLarge: OrderCancelImgLarge
};

export type IconProps = {
	name: keyof typeof iconNames;
	params?: any;
};
const withargs = ['logout','collapse']
export default function Icon({ name, params }: IconProps) {		
	let args: object = { params: params };
	if(name == 'logout') {
		return React.createElement(Logout, args);
	}else if(name == 'collapse') {
		return React.createElement(Collapse, args);
	}else {
		const IconComponent = iconNames[name];
		return <IconComponent />;
	}
}
